---
version: "2.1"
volumes:
  media:
   name: media
   driver_opts:
      type: "nfs"
      o: "addr=192.168.1.20,nolock,soft,rw"
      device: ":/mnt/tank/media"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - /home/piotr/heimdall/config:/config
    ports:
      - 8000:80
      - 443:443
    restart: unless-stopped
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - 8080:8080
      - 8181:8181
      - 44343:44343
    volumes:
      - /home/piotr/nginx-proxy-manager/data:/data
      - /home/piotr/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - /home/piotr/transmission:/config
      - media:/downloads
      - /home/piotr/transmission/incomplete:/incomplete
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /home/piotr/plex/data:/config
      - media:/media
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - JELLYFIN_PublishedServerUrl=192.168.1.21 #optional
    volumes:
      - /home/piotr/jellyfin/library:/config
      - media:/data
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
